# Generated by Django 4.2.5 on 2024-03-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='موجود/نا موجود'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف شده/حذف نشده'),
        ),
    ]
