# Generated by Django 4.2.5 on 2024-03-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_products_is_active_alter_products_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
    ]
